name: web2py-dev

services:
  postgres:
    image: 'postgres:16'
    container_name: pg16
    environment:
      - POSTGRES_PASSWORD=dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  web2py:
    build:
      context: .
      dockerfile: web2py.Dockerfile
    container_name: web2py
    depends_on:
      postgres:
        condition: service_started
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - web2py:/opt/web2py
      - vscode-server:/root/.vscode-server
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'

volumes:
  postgres_data:
    driver: local
  web2py:
    driver: local
  vscode-server:
    driver: local