services:
  pg16-dev:
    container_name: pg16-dev
    build:
      context: .
      dockerfile: pg16.Dockerfile
    environment:
      - POSTGRES_PASSWORD=dev
    volumes:
      - pg16-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg16-dev:
    driver: local
