include:
  - pg16.compose.yaml

name: web2py

services:
  v3-dev:
    container_name: v3-dev
    build:
      context: .
      dockerfile: v3.Dockerfile
    depends_on:
      - pg16-dev
    environment:
      - POSTGRES_HOST=pg16-dev
    volumes:
      - ./v3-dev:/opt/web2py
      - ./Upload-Data:/Upload-Data
      - site-packages-v3-dev:/usr/local/lib/python3.10/site-packages
      - vscode-server-v3-dev:/root/.vscode-server
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'

volumes:
  site-packages-v3-dev:
    driver: local
  vscode-server-v3-dev:
    driver: local
